services:
  ndfl-calculation-bot:
    build: .
    container_name: ndfl-calculation-bot
    environment:
      - BOT_DEVELOPER=BOT_DEVELOPER
      - BOT_VERSION=BOT_VERSION
      - BOT_TOKEN=BOT_TOKEN